# Step 2: Finding Relevant Data

Add your API key to the cell below then run it.

In [23]:
import openai
openai.api_base = "https://api.openai.com/v1"
openai.api_key = ""

The code below loads in the embeddings you previously created. Run it as-is.

In [24]:
import numpy as np
import pandas as pd

df = pd.read_csv("embeddings.csv", index_col=0)
df["embeddings"] = df["embeddings"].apply(eval).apply(np.array)
df

,text,embeddings
0,"On 6 February 2023, at 04:17 TRT (01:17 UTC), ...","[-0.007865791209042072, -0.01488738413900137, ..."
1,The Mw 7.8 earthquake is the largest in Turkey...,"[0.00019888307724613696, -0.022314351052045822..."
2,There was widespread damage in an area of abou...,"[-0.003678650129586458, -0.020112549886107445,..."
3,Central southern Turkey and northwestern Syria...,"[-0.005976187530905008, -0.011475914157927036,..."
4,The EAF has produced large or damaging earthqu...,"[0.0002380282385274768, -0.02387528494000435, ..."
...,...,...
96,The International Seismological Centre has a b...,"[-0.004583664704114199, -0.009662682190537453,..."
97,The International Seismological Centre has a b...,"[-0.004807258490473032, -0.01684679090976715, ..."
98,"Erdik, M., Tümsa, M. B. D., Pınar, A., Altunel...","[-0.006729048676788807, -0.04049292206764221, ..."
99,"""Kahramanmaraş Supersite science page"". Group ...","[0.0036264623049646616, -0.007848413661122322,..."
100,"Schmitt, R.; Herman, M.; Barnhart, W.; Furlong...","[-0.01565597392618656, -0.022238751873373985, ..."

## TODO 1: Create Embeddings for the User's Question

In the previous exercise, you were given the code to create embeddings for everything in the dataset. Now your task is to create embeddings for just one string: the user's question. Assign the result to the variable `question_embeddings`. This variable should contain a list of 1,536 floating point numbers, and the provided code will print the first 100 once `question_embeddings` has been created correctly.

If you're getting stuck, you can click to reveal the solution then copy and paste this into the cell below.

---

<details>
    <summary style="cursor: pointer"><strong>Solution (click to show/hide)</strong></summary>

```python
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
USER_QUESTION = """What were the estimated damages of the 2023 \
Turkey-Syria earthquake?"""

# Generate the embedding response
response = openai.Embedding.create(
    input=USER_QUESTION,
    engine=EMBEDDING_MODEL_NAME
)

# Extract the embeddings from the response
question_embeddings = response["data"][0]["embedding"]

print(question_embeddings[:100])
```

</details>

In [25]:
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
USER_QUESTION = """What were the estimated damages of the 2023 \
Turkey-Syria earthquake?"""

# Generate the embedding response
response = openai.embeddings.create(
    input=USER_QUESTION,
    model=EMBEDDING_MODEL_NAME
)

# Extract the embeddings from the response
question_embeddings = response.data[0].embedding

print(question_embeddings[:100])

[0.0055134412832558155, -0.024900270625948906, 0.0023327376693487167, -0.012057743035256863, -0.02148180454969406, 0.0025389099027961493, -0.03381222486495972, -0.013101905584335327, 0.002271218691021204, -0.015004009008407593, 0.0162410419434309, 0.044320352375507355, -0.010262050665915012, -0.013308077119290829, 0.015070516616106033, -0.005400379188358784, 0.012456785887479782, -0.013135158456861973, 0.008339994587004185, -0.0057362401857972145, -0.0074754017405211926, 0.011472480371594429, 0.012396929785609245, -0.009018367156386375, 0.015123722143471241, 0.032162848860025406, 0.008027411065995693, -0.0023377256002277136, -0.0007943445816636086, -0.012204058468341827, 0.005523417145013809, -0.006550952792167664, -0.023450415581464767, 0.015256736427545547, -0.03240227326750755, -0.007575162220746279, 0.0068834880366921425, -0.0048450445756316185, 0.023344002664089203, -0.007927650585770607, 0.010075830854475498, 0.028624670580029488, 0.01296889130026102, -0.007708176504820585, -0.01754458248615265, -0.00427973410114646, 0.01725194975733757, 0.0030925816390663385, -0.004825092386454344, 0.021295584738254547, 0.013068651780486107, 0.026762470602989197, -0.03782925754785538, -0.020377784967422485, -0.015589271672070026, -0.016440562903881073, -0.0014066258445382118, -0.019579699262976646, -0.0001513037277618423, -0.011572240851819515, 0.009291046299040318, -0.006836933083832264, -0.02875768393278122, 0.00137919164262712, -0.013939894735813141, -0.015270037576556206, 0.007575162220746279, -0.02098965086042881, -0.019606303423643112, 0.010867265053093433, 0.05009317398071289, 0.04764571040868759, 0.0009219550993293524, -0.05708972364664078, 0.0352487787604332, -0.004791839048266411, 0.017917022109031677, -0.006517698988318443, -0.0072958325035870075, 0.0024241849314421415, 0.03644590824842453, -0.020244771614670753, -0.003784255823120475, 0.0014623255701735616, 0.03155098482966423, -0.0008463032427243888, 0.005207508336752653, 0.009377505630254745, -0.029236534610390663, 0.017877116799354553, 0.012835877016186714, 0.03040706180036068, -0.0034384187310934067, 0.009856357239186764, 0.0007860311889089644, -0.007674923166632652, -0.02565845102071762, 0.01703912764787674, -0.015615874901413918, -0.045889921486377716]

## TODO 2: Find Cosine Distances

Create a new list called `distances`, which represents the cosine distances between `question_embeddings` and each value in the `'embeddings'` column of `df`.

If you're getting stuck, you can click to reveal the solution then copy and paste this into the cell below.

---

<details>
    <summary style="cursor: pointer"><strong>Solution (click to show/hide)</strong></summary>

```python
from openai.embeddings_utils import distances_from_embeddings

# Create a list containing the distances from question_embeddings
distances = distances_from_embeddings(
    question_embeddings,
    df["embeddings"],
    distance_metric="cosine"
)

print(distances[:100])
```

</details>

In [26]:
from sklearn.metrics.pairwise import cosine_distances
import numpy as np

# Create a list containing the distances from question_embeddings
distances = cosine_distances(
    [question_embeddings],
    np.array(df["embeddings"].tolist())
)[0]

print(distances[:100])

[0.11680921 0.13425349 0.08788037 0.17517923 0.15367086 0.14492131
 0.14775698 0.159353   0.14752053 0.16198672 0.19435548 0.14276406
 0.16905622 0.18120244 0.16958621 0.18445703 0.1237976  0.15978569
 0.16502862 0.16986086 0.15978495 0.16133453 0.14730919 0.15206818
 0.17780499 0.18989791 0.28042573 0.29602316 0.29602316 0.28036399
 0.28042573 0.29613832 0.29600666 0.28031465 0.28031465 0.29613832
 0.29613832 0.28031465 0.28051105 0.29583206 0.29583206 0.28051105
 0.16217996 0.17149398 0.14954191 0.10236716 0.11647028 0.17283113
 0.18680691 0.18013376 0.15284384 0.15710284 0.19234133 0.1556947
 0.14800631 0.18681407 0.17376953 0.19594515 0.2056542  0.23351489
 0.16291092 0.19517269 0.16799712 0.18658373 0.22202754 0.17614713
 0.15130424 0.21754733 0.18259422 0.1696385  0.12209208 0.20100958
 0.19557495 0.15639868 0.22653048 0.18322249 0.23747209 0.18008396
 0.15889732 0.18507796 0.17842092 0.16477761 0.13019483 0.13649616
 0.1981845  0.14263247 0.12367202 0.14220186 0.14790135 0.13922988
 0.1441899  0.15152715 0.15904144 0.14871559 0.129283   0.2276705
 0.19239289 0.19390514 0.13153001 0.21130835]

## Sorting by Distance

The code below uses the `distances` list to update `df` then sorts `df` to find the most related rows. Shorter distance means more similarity, so we'll use an ascending sorting order. Run the cell below as-is.

In [27]:
df["distances"] = distances
df.sort_values(by="distances", ascending=True, inplace=True)
df.head(5)

,text,embeddings,distances
2,There was widespread damage in an area of abou...,"[-0.003678650129586458, -0.020112549886107445,...",0.087880
45,The USGS Prompt Assessment of Global Earthquak...,"[-0.005647257436066866, -0.02702903561294079, ...",0.102367
46,The United Nations Development Programme estim...,"[0.012168490327894688, -0.0028820110019296408,...",0.116470
0,"On 6 February 2023, at 04:17 TRT (01:17 UTC), ...","[-0.007865791209042072, -0.01488738413900137, ...",0.116809
70,The Turkish Government was criticized on socia...,"[-0.0005342955118976533, -8.552115468773991e-0...",0.122092

Great, now we have the dataset sorted from most relevant to least relevant! Let's save this as a CSV so we can load it in the next step and compose a custom prompt.

Run the cell below as-is.

In [28]:
df.to_csv("distances.csv")